project_name: gen-statsd
before:
  hooks:
    - go mod tidy
builds:
  - 
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - solaris
      - illumos
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      -
        goarch: 386
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: openbsd
        goarch: arm
    ldflags: 
      - -X github.com/circonus-labs/gen-statsd/internal/release.VERSION={{.Version}} 
      - -X github.com/circonus-labs/gen-statsd/internal/release.COMMIT={{.ShortCommit}} 
      - -X github.com/circonus-labs/gen-statsd/internal/release.DATE={{.Date}} 
      - -X github.com/circonus-labs/gen-statsd/internal/release.TAG={{.Tag}}

# dockers:
#   -
#     goos: linux
#     goarch: amd64
#     goarm: ''
#     binaries:
#       - gen-statsd
#     image_templates:
#       - "circonus/{{.ProjectName}}:{{.Major}}.{{.Minor}}.{{.Patch}}"
#       - "circonus/{{.ProjectName}}:{{.Major}}.{{.Minor}}"
#       - "circonus/{{.ProjectName}}:latest"
#     skip_push: false
#     dockerfile: deploy/docker/x86_64/Dockerfile
#     build_flag_templates:
#       - "--label=org.label-schema.schema-version=1.0"
#       - "--label=org.label-schema.version={{.Version}}"
#       - "--label=org.label-schema.name={{.ProjectName}}"
#   -
#     goos: linux
#     goarch: arm64
#     goarm: ''
#     binaries:
#       - gen-statsd
#     image_templates:
#       - "circonus/{{.ProjectName}}:{{.Major}}.{{.Minor}}.{{.Patch}}-arm64"
#       - "circonus/{{.ProjectName}}:{{.Major}}.{{.Minor}}-arm64"
#       - "circonus/{{.ProjectName}}:latest-arm64"
#     skip_push: false
#     dockerfile: deploy/docker/arm64/Dockerfile
#     build_flag_templates:
#       - "--label=org.label-schema.schema-version=1.0"
#       - "--label=org.label-schema.version={{.Version}}"
#       - "--label=org.label-schema.name={{.ProjectName}}"

archives:
  - 
    id: default
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz
    replacements:
      amd64: x86_64
    format_overrides:
      -
        goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

release:
    github:
        owner: circonus-labs
        name: gen-statsd

    prerelease: auto

checksum:
  name_template: "{{.ProjectName}}_checksums.txt"

