project_name: gen-statsd
before:
  hooks:
    - go mod tidy
builds:
  - 
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - solaris
      - illumos
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      -
        goarch: 386
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: openbsd
        goarch: arm
checksum:
  name_template: "{{.ProjectName}}_checksums.txt"
snapshot:
  name_template: "SNAPSHOT-{{.Commit}}"