name: goreleaser
on:
  push:
    tags:
     - '*'
jobs:
  vet_lint_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.2'
    
    # Install dependencies
    - name: Install dependencies
      run: go get -u golang.org/x/lint/golint

    # Run vet and lint
    - name: Vet and lint
      run: |
        go vet .
        golint .

    # Run tests
    - name: Run tests
      run: go test -v ./...
  goreleaser:
    runs-on: ubuntu-latest
    needs: vet_lint_test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - 
        name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}